-- =====================================================
-- Nepal Local Levels (from custom CSV)
-- Full names preserved: 'X Rural Municipality', 'Y Municipality'
-- =====================================================

INSERT INTO local_levels (district_id, name, type) VALUES (12, 'Phaktanlung Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (12, 'Mikwakhola Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (12, 'Meringden Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (12, 'Maiwakhola Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (12, 'Aatharai Tribeni Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (12, 'Phungling Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (12, 'Pathivara Yangwarak Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (12, 'Sirijanga Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (12, 'Sidingba Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (9, 'Bhotkhola Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (9, 'Makalu Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (9, 'Silichong Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (9, 'Chichila Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (9, 'Sabhapokhari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (9, 'Khandabari Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (9, 'Panchakhapan Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (9, 'Chainapur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (9, 'Madi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (9, 'Dharmadevi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (10, 'Khumbu Pasanglhamu Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (10, 'Mahakulung Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (10, 'Sotang Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (10, 'Mapya Dudhkoshi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (10, 'Thulung Dudhkoshi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (10, 'Necha Salyan Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (10, 'Solu Dhudhakunda Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (10, 'Likhu Pike Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (7, 'Chishankhu Gadhi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (7, 'Siddhicharan Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (7, 'Molung Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (7, 'Khiji Demba Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (7, 'Likhu Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (7, 'Champadevi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (7, 'Sunkoshi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (7, 'Manebhanjyang Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (5, 'Kepilasgadhi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (5, 'Aiselukharka Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (5, 'Rawa Besi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (5, 'Halesi Tuwachung Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (5, 'Diktel Rupakot Majhuwagadhi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (5, 'Sakela Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (5, 'Diprung Chuichumma Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (5, 'Khotehang Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (5, 'Jante Dhunga Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (5, 'Baraha Pokhari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (1, 'Shadananda Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (1, 'Salpa Silichho Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (1, 'Temkemaiyum Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (1, 'Bhojpur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (1, 'Arun Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (1, 'Pauwa Dunma Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (1, 'Ramprasad Rai Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (1, 'Hatuwagadhi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (1, 'Aamchowk Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (2, 'Mahalaxmi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (2, 'Pakhribas Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (2, 'Chhathar Jorpati Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (2, 'Dhankuta Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (2, 'Shahidbhumi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (2, 'Sangurigadhi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (2, 'Chaubise Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (13, 'Aatharai Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (13, 'Phedap Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (13, 'Menchhayayem Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (13, 'Myanglung Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (13, 'Laligurans Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (13, 'Chhathar Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (8, 'Yangbarak Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (8, 'Hilihan Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (8, 'Falelung Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (8, 'Phidim Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (8, 'Falgunanda Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (8, 'Kummayak Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (8, 'Tumbewa Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (8, 'Miklajung Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (3, 'Mai Jogmai Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (3, 'Sandakpur Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (3, 'Illam Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (3, 'Deumai Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (3, 'Fakfokathum Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (3, 'Mangsebung Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (3, 'Chulachuli Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (3, 'Mai Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (3, 'Suryodaya Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (3, 'Rong Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (4, 'Mechinagar Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (4, 'Buddhashanti Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (4, 'Arjundhara Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (4, 'Kankai Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (4, 'Shivasatakshi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (4, 'Kamal Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (4, 'Damak Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (4, 'Gauradaha Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (4, 'Gauriganj Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (4, 'Jhapa Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (4, 'Barhadashi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (4, 'Birtamod Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (4, 'Haldibari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (4, 'Bhadrapur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (4, 'Kachanakawal Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (6, 'Miklajung Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (6, 'Letang Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (6, 'Kerabari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (6, 'Sundarharaicha Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (6, 'Belbari Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (6, 'Kanepokhari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (6, 'Pathari Shanishchare Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (6, 'Urlabari Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (6, 'Ratuwamai Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (6, 'Sunwarshi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (6, 'Rangeli Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (6, 'Gramthan Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (6, 'Budhiganga Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (6, 'Biratnagar Metropolitian City', 'Metropolitan');
INSERT INTO local_levels (district_id, name, type) VALUES (6, 'Katahari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (6, 'Dhanapalthan Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (6, 'Jahada Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (11, 'Dharan Sub-Metropolitian City', 'Sub-Metropolitan');
INSERT INTO local_levels (district_id, name, type) VALUES (11, 'Barahachhetra Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (11, 'Koshi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (11, 'Bhokraha Narsingh Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (11, 'Ramdhuni Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (11, 'Itahari Sub-Metropolitian City', 'Sub-Metropolitan');
INSERT INTO local_levels (district_id, name, type) VALUES (11, 'Duhabi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (11, 'Gadhi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (11, 'Inaruwa Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (11, 'Harinagar Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (11, 'Dewangunj Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (11, 'Barju Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (14, 'Belaka Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (14, 'Chaudandigadhi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (14, 'Triyuga Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (14, 'Rautamai Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (14, 'Limchunbung Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (14, 'Tapli Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (14, 'Katari Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (14, 'Udayapurgadhi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (20, 'Saptakoshi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (20, 'Kanchanrup Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (20, 'Agnisair Krishna Sabaran Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (20, 'Rupani Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (20, 'Shambhunath Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (20, 'Khadak Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (20, 'Surunga Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (20, 'Balan-Bihul Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (20, 'Bode Barsain Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (20, 'Dakneshwori Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (20, 'Rajgadh Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (20, 'Bishnupur Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (20, 'Rajbiraj Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (20, 'Mahadewa Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (20, 'Tirahut Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (20, 'Hanumannagar Kankalini Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (20, 'Tilathi Koiladi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (20, 'Chhinnamasta Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (22, 'Lahan Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (22, 'Dhangadhimai Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (22, 'Golbazar Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (22, 'Mirchaiya Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (22, 'Karjanha Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (22, 'Kalyanpur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (22, 'Naraha Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (22, 'Bishnupur Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (22, 'Arnama Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (22, 'Sukhipur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (22, 'Laxmipur Patari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (22, 'Sakhuwa Nankarkatti Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (22, 'Bhagawanpur Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (22, 'Nawarajpur Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (22, 'Bariyarpatti Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (22, 'Aurahi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (22, 'Siraha Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (16, 'Ganeshman Charnath Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (16, 'Dhanushadham Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (16, 'Mithila Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (16, 'Bateshwor Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (16, 'Chhireshwornath Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (16, 'Laxminiya Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (16, 'Mithila Bihari Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (16, 'Hansapur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (16, 'Sabaila Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (16, 'Shahidnagar Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (16, 'Kamala Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (16, 'Janak Nandini Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (16, 'Bideha Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (16, 'Aurahi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (16, 'Janakpurdham Sub-Metropolitian City', 'Sub-Metropolitan');
INSERT INTO local_levels (district_id, name, type) VALUES (16, 'Dhanauji Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (16, 'Nagarain Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (16, 'Mukhiyapatti Musaharmiya Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (17, 'Bardibas Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (17, 'Gaushala Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (17, 'Sonama Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (17, 'Aurahi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (17, 'Bhangaha Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (17, 'Loharpatti Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (17, 'Balawa Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (17, 'Ram Gopalpur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (17, 'Samsi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (17, 'Manara Shisawa Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (17, 'Ekadara Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (17, 'Mahottari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (17, 'Pipara Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (17, 'Matihani Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (17, 'Jaleshwor Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Lalbandi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Hariwan Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Bagmati Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Barahathawa Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Haripur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Ishworpur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Haripurwa Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Parsa Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Brahmapuri Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Chandranagar Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Kabilashi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Chakraghatta Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Basbariya Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Dhanakaul Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Ramnagar Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Balara Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Godaita Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Bishnu Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Kaudena Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (21, 'Malangawa Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (19, 'Chandrapur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (19, 'Gujara Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (19, 'Phatuwa Bijayapur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (19, 'Katahariya Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (19, 'Brindaban Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (19, 'Gadhimai Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (19, 'Madhav Narayan Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (19, 'Garuda Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (19, 'Dewahi Gonahi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (19, 'Maulapur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (19, 'Boudhimai Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (19, 'Paroha Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (19, 'Rajpur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (19, 'Yamunamai Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (19, 'Durga Bhagawati Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (19, 'Rajdevi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (19, 'Gaur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (19, 'Ishanath Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (15, 'Nijagadh Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (15, 'Kolhabi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (15, 'Jitpur Simara Sub-Metropolitian City', 'Sub-Metropolitan');
INSERT INTO local_levels (district_id, name, type) VALUES (15, 'Parawanipur Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (15, 'Prasauni Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (15, 'Bishrampur Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (15, 'Pheta Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (15, 'Kalaiya Sub-Metropolitian City', 'Sub-Metropolitan');
INSERT INTO local_levels (district_id, name, type) VALUES (15, 'Karaiyamai Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (15, 'Baragadhi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (15, 'Aadarsha Kotwal Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (15, 'Simroungadh Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (15, 'Pacharauta Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (15, 'Mahagadhimai Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (15, 'Devtal Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (15, 'Subarna Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (18, 'Thori Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (18, 'Jirabhawani Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (18, 'Jagarnathpur Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (18, 'Paterwa Sugauli Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (18, 'Sakhuwa Prasauni Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (18, 'Parsagadhi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (18, 'Birgunj Metropolitian City', 'Metropolitan');
INSERT INTO local_levels (district_id, name, type) VALUES (18, 'Bahudarmai Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (18, 'Pokhariya Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (18, 'Kalikamai Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (18, 'Dhobini Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (18, 'Chhipaharmai Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (18, 'Pakaha Mainpur Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (18, 'Bindabasini Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (26, 'Gaurishankar Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (26, 'Bigu Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (26, 'Kalinchowk Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (26, 'Baiteshwor Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (26, 'Jiri Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (26, 'Tamakoshi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (26, 'Melung Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (26, 'Shailung Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (26, 'Bhimeshwor Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (35, 'Bhotekoshi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (35, 'Jugal Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (35, 'Panchpokhari Thangpal Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (35, 'Helambu Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (35, 'Melanchi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (35, 'Indrawoti Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (35, 'Choutara Sangachowkgadhi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (35, 'Balephi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (35, 'Bahrabise Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (35, 'Tripurasundari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (35, 'Lisankhu Pakhar Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (35, 'Sunkoshi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (33, 'Gosaikunda Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (33, 'Aamachhodingmo Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (33, 'Uttargaya Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (33, 'Kalika Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (33, 'Naukunda Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (25, 'Rubi Valley Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (25, 'Khaniyabas Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (25, 'Ganga Jamuna Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (25, 'Tripurasundari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (25, 'Netrawati Dabjong Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (25, 'Nilkhantha Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (25, 'Jwalamukhi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (25, 'Siddhalek Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (25, 'Benighat Rorang Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (25, 'Gajuri Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (25, 'Galchhi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (25, 'Thakre Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (25, 'Dhunibenshi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (31, 'Dupcheshwor Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (31, 'Tadi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (31, 'Suryagadhi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (31, 'Bidur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (31, 'Kispang Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (31, 'Myagang Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (31, 'Tarakeshwor Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (31, 'Belkotgadhi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (31, 'Likhu Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (31, 'Panchakanya Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (31, 'Shivapuri Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (31, 'Kakani Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (27, 'Shankharapur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (27, 'Kageshwori Manahara Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (27, 'Gokarneshwor Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (27, 'Budhanilkhantha Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (27, 'Tokha Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (27, 'Tarakeshwor Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (27, 'Nagarjun Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (27, 'Kathmandu Metropolitian City', 'Metropolitan');
INSERT INTO local_levels (district_id, name, type) VALUES (27, 'Kirtipur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (27, 'Chandragiri Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (27, 'Dakshinkali Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (23, 'Changunarayan Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (23, 'Bhaktapur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (23, 'Madhyapur Thimi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (23, 'Suryabinayak Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (29, 'Mahalaxmi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (29, 'Lalitpur Metropolitian City', 'Metropolitan');
INSERT INTO local_levels (district_id, name, type) VALUES (29, 'Godawari Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (29, 'Konjyosom Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (29, 'Mahankal Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (29, 'Bagmati Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (28, 'Chauri Deurali Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (28, 'Bhumlu Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (28, 'Mandan Deupur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (28, 'Banepa Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (28, 'Dhulikhel Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (28, 'Panchkhal Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (28, 'Temal Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (28, 'Namobuddha Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (28, 'Panauti Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (28, 'Bethanchowk Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (28, 'Roshi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (28, 'Mahabharat Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (28, 'Khanikhola Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (32, 'Umakunda Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (32, 'Gokulganga Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (32, 'Likhu Tamakoshi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (32, 'Ramechhap Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (32, 'Manthali  Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (32, 'Khandadevi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (32, 'Doramba Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (32, 'Sunapati Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (34, 'Dudhouli Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (34, 'Phikkal Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (34, 'Tinpatan Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (34, 'Golanjor Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (34, 'Kamalamai Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (34, 'Sunkoshi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (34, 'Ghyanglekha Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (34, 'Marin Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (34, 'Hariharpurgaghi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (30, 'Indrasarowar Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (30, 'Thaha Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (30, 'Kailash Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (30, 'Raksirang Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (30, 'Manahari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (30, 'Hetauda Sub-Metropolitian City', 'Sub-Metropolitan');
INSERT INTO local_levels (district_id, name, type) VALUES (30, 'Bhimphedi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (30, 'Makawanpurgadhi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (30, 'Bakaiya Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (30, 'Bagmati Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (24, 'Rapti Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (24, 'Kalika Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (24, 'Ichchha Kamana Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (24, 'Bharatpur Metropolitian City', 'Metropolitan');
INSERT INTO local_levels (district_id, name, type) VALUES (24, 'Ratnanagar Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (24, 'Khairahani Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (24, 'Madi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (37, 'Chumanubri Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (37, 'Ajirkot Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (37, 'Barpak Sulikot Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (37, 'Dharche Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (37, 'Aarughat Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (37, 'Bhimsenthapa Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (37, 'Siranchowk Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (37, 'Palungtar Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (37, 'Gorkha Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (37, 'Shahid Lakhan Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (37, 'Gandaki Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (40, 'Narpa Bhumi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (40, 'Manang Ngisyang Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (40, 'Chame Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (40, 'Nason Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (41, 'Lo Ghekar Damodarkunda Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (41, 'Gharpajhong Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (41, 'Varagung Muktichhetra Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (41, 'Lomanthang Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (41, 'Thasang Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (42, 'Annapurna Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (42, 'Raghuganga Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (42, 'Dhawalagiri Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (42, 'Malika Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (42, 'Mangala Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (42, 'Beni Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (38, 'Madi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (38, 'Machhapuchchhre Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (38, 'Annapurna Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (38, 'Pokhara Metropolitian City', 'Metropolitan');
INSERT INTO local_levels (district_id, name, type) VALUES (38, 'Rupa Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (39, 'Dordi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (39, 'Marshyangdi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (39, 'Kwhola Sothar Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (39, 'Madhya Nepal Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (39, 'Bensishahar Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (39, 'Sundarbazar Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (39, 'Rainas Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (39, 'Dudhapokhari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (46, 'Bhanu Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (46, 'Byas Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (46, 'Myagde Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (46, 'Shuklagandaki Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (46, 'Bhimad Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (46, 'Ghiring Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (46, 'Rhishing Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (46, 'Devghat Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (46, 'Bandipur Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (46, 'Aanbu Khaireni Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (43, 'Gaidakot Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (43, 'Bulingtar Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (43, 'Baudikali Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (43, 'Hupsekot Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (43, 'Devchuli Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (43, 'Kawasoti Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (43, 'Madhya Bindu Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (43, 'Binayi Tribeni Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (45, 'Putalibazar Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (45, 'Phedikhola Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (45, 'Aandhikhola Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (45, 'Arjun Choupari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (45, 'Bhirkot Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (45, 'Biruwa Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (45, 'Harinas Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (45, 'Chapakot Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (45, 'Walling Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (45, 'Galyang Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (45, 'Kaligandaki Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (44, 'Modi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (44, 'Jaljala Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (44, 'Kushma Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (44, 'Phalebas Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (44, 'Mahashila Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (44, 'Bihadi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (44, 'Paiyu Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (36, 'Baglung Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (36, 'Kathekhola Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (36, 'Tarakhola Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (36, 'Tamankhola Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (36, 'Dhorpatan Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (36, 'Nisikhola Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (36, 'Badigad Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (36, 'Galkot Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (36, 'Bareng Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (36, 'Jaimuni Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (51, 'Putha Uttanganga Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (51, 'Sisne Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (51, 'Bhoome Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (57, 'Sunchhahari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (57, 'Thawang Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (57, 'Pariwartan Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (57, 'Gangadev Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (57, 'Madi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (57, 'Tribeni Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (57, 'Rolpa Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (57, 'Runtigadhi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (57, 'Sunil Smriti Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (57, 'Lungri Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (56, 'Gaumukhi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (56, 'Naubahini Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (56, 'Jhimaruk Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (56, 'Pyuthan Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (56, 'Sworgadwari Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (56, 'Mandavi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (56, 'Mallarani Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (56, 'Aairawati Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (56, 'Sarumarani Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (52, 'Kali Gandaki Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (52, 'Satyawoti Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (52, 'Chandrakot Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (52, 'Musikot Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (52, 'Isma Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (52, 'Malika Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (52, 'Madane Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (52, 'Dhurkot Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (52, 'Resunga Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (52, 'Gulmi Durbar Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (52, 'Chhatrakot Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (52, 'Ruruchhetra Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (47, 'Chhatradev Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (47, 'Malarani Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (47, 'Bhumikasthan Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (47, 'Sandhikharka Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (47, 'Panini Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (47, 'Shitaganga Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (55, 'Rampur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (55, 'Purbakhola Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (55, 'Rambha Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (55, 'Baganaskali Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (55, 'Tansen Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (55, 'Ribdikot Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (55, 'Rainadevi Chhahara Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (55, 'Tinau Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (55, 'Mathagadhi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (55, 'Nisdi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (54, 'Bardaghat Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (54, 'Sunawal Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (54, 'Ramgram Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (54, 'Palhinandan Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (54, 'Sarawal Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (54, 'Pratapapur Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (54, 'Susta Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (58, 'Devdaha Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (58, 'Butwal Sub-Metropolitian City', 'Sub-Metropolitan');
INSERT INTO local_levels (district_id, name, type) VALUES (58, 'Sainamaina Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (58, 'Kanchan Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (58, 'Gaidahawa Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (58, 'Suddhodhan Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (58, 'Siyari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (58, 'Tilottama Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (58, 'Om Satiya Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (58, 'Rohini Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (58, 'Siddharthanagar Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (58, 'Mayadevi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (58, 'Lumbini Sanskritik Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (58, 'Kotahimai Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (58, 'Sammarimai Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (58, 'Marchawari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (53, 'Banganga Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (53, 'Buddhabhumi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (53, 'Shivaraj Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (53, 'Bijayanagar Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (53, 'Krishnanagar Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (53, 'Maharajganj Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (53, 'Kapilbastu Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (53, 'Yasodhara Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (53, 'Mayadevi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (53, 'Shuddhodhan Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (50, 'Bangalachuli Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (50, 'Ghorahi Sub-Metropolitian City', 'Sub-Metropolitan');
INSERT INTO local_levels (district_id, name, type) VALUES (50, 'Tulsipur Sub-Metropolitian City', 'Sub-Metropolitan');
INSERT INTO local_levels (district_id, name, type) VALUES (50, 'Shantinagar Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (50, 'Babai Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (50, 'Dangisharan Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (50, 'Lamahi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (50, 'Rapti Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (50, 'Gadhawa Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (50, 'Rajpur Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (48, 'Rapti Sonari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (48, 'Kohalpur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (48, 'Baijanath Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (48, 'Khajura Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (48, 'Janaki Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (48, 'Nepalganj Sub-Metropolitian City', 'Sub-Metropolitan');
INSERT INTO local_levels (district_id, name, type) VALUES (48, 'Duduwa Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (48, 'Narainapur Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (49, 'Bansgadhi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (49, 'Barbardiya Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (49, 'Thakurbaba Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (49, 'Geruwa Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (49, 'Rajapur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (49, 'Madhuwan Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (49, 'Gulariya Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (49, 'Badhaiyatal Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (60, 'Dolpo Buddha Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (60, 'Shey Phoksundo Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (60, 'Jagadulla Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (60, 'Mudkechula Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (60, 'Tripurasundari Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (60, 'Thulibheri Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (60, 'Kaike Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (60, 'Chharka Tangsong Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (65, 'Mugumakarmarog Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (65, 'Chhayanath Rara Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (65, 'Soru Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (65, 'Khatyad Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (61, 'Chankheli Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (61, 'Kharpunath Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (61, 'Simkot Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (61, 'Namkha Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (61, 'Sarkegad Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (61, 'Adanchuli Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (61, 'Tanjakot Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (63, 'Patarasi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (63, 'Kanaka Sundari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (63, 'Sinja Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (63, 'Chandannath Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (63, 'Guthichaur Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (63, 'Tatopani Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (63, 'Tila Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (63, 'Hima Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (64, 'Palata Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (64, 'Pachal Jharana Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (64, 'Raskot Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (64, 'Sanni Tribeni Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (64, 'Naraharinath Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (64, 'Khandachakra Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (64, 'Tilagupha Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (64, 'Mahawai Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (64, 'Shuva Kalika Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (59, 'Naumule Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (59, 'Mahabu Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (59, 'Bhairabi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (59, 'Thantikandh Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (59, 'Aathbis Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (59, 'Chamunda Bindrasaini Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (59, 'Dullu Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (59, 'Narayan Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (59, 'Bhagawatimai Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (59, 'Dungeshwor Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (59, 'Gurans Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (62, 'Barekot Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (62, 'Kuse Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (62, 'Junichande Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (62, 'Chhedagad Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (62, 'Shivalaya Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (62, 'Bheri Malika Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (62, 'Nalgad Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (68, 'Aathabisakot Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (68, 'Sanibheri Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (68, 'Banphikot Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (68, 'Musikot Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (68, 'Tribeni Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (68, 'Chaurjahari Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (66, 'Darma Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (66, 'Kumakh Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (66, 'Banagad Kupinde Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (66, 'Siddha Kumakh Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (66, 'Bagachour Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (66, 'Chhatreshwori Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (66, 'Sharada Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (66, 'Kalimati Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (66, 'Tribeni Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (66, 'Kapurkot Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (67, 'Simta Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (67, 'Chingad Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (67, 'Lekabeshi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (67, 'Gurbhakot Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (67, 'Bheriganga Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (67, 'Birendranagar Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (67, 'Barahatal Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (67, 'Panchapuri Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (67, 'Chaukune Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (72, 'Himali Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (72, 'Gaumul Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (72, 'Budhinanda Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (72, 'Swamikartik Khapar Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (72, 'Jagannath Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (72, 'Badimalika Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (72, 'Khaptad Chhededaha Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (72, 'Budhiganga Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (72, 'Tribeni Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (71, 'Saipal Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (71, 'Bungal Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (71, 'Surma Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (71, 'Talkot Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (71, 'Masta Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (71, 'Jayaprithbi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (71, 'Chhabis Pathibhara Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (71, 'Durgathali Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (71, 'Kedarsyun Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (71, 'Bitthadchir Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (71, 'Thalara Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (71, 'Khaptad Chhanna Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (74, 'Byas Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (74, 'Duhun Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (74, 'Mahakali Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (74, 'Naugad  Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (74, 'Apihimal Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (74, 'Marma Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (74, 'Shailyashikhar Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (74, 'Malikarjun Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (74, 'Lekam Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (70, 'Dilasaini Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (70, 'Dogada Kedar Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (70, 'Puchaundi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (70, 'Surnaya Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (70, 'Dasharathchand Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (70, 'Pancheshwor Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (70, 'Shivanath Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (70, 'Melauli Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (70, 'Patan Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (70, 'Sigas Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (73, 'Nawadurga Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (73, 'Amargadhi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (73, 'Ajayameru Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (73, 'Bhageshwor Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (73, 'Parashuram Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (73, 'Aalital Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (73, 'Ganyapdhura Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (75, 'Purbichouki Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (75, 'Sayal Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (75, 'Aadarsha Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (75, 'Shikhar Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (75, 'Dipayal Silgadhi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (75, 'K.I. Singh Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (75, 'Bogatan Phudsil Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (75, 'Badi Kedar Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (75, 'Jorayal Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (69, 'Panchdebal Binayak Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (69, 'Ramaroshan Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (69, 'Mellekh Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (69, 'Sanphebagar Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (69, 'Chaurpati Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (69, 'Mangalsen Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (69, 'Bannigadhi Jayagadh Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (69, 'Kamal bazar Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (69, 'Dhakari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (69, 'Turmakhand Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (76, 'Mohanyal Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (76, 'Chure Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (76, 'Godawari Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (76, 'Gauriganga Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (76, 'Ghodaghodi Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (76, 'Bardagoriya Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (76, 'Lamki Chuha Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (76, 'Janaki Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (76, 'Joshipur Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (76, 'Tikapur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (76, 'Bhajani Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (76, 'Kailari Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (76, 'Dhangadhi Sub-Metropolitian City', 'Sub-Metropolitan');
INSERT INTO local_levels (district_id, name, type) VALUES (77, 'Krishnapur Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (77, 'Shuklaphanta Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (77, 'Bedkot Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (77, 'Bhimdatta Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (77, 'Dodhara Chandani Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (77, 'Laljhadi Rural Municipality', 'Rural Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (77, 'Punarbas Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (77, 'Belouri Municipality', 'Municipality');
INSERT INTO local_levels (district_id, name, type) VALUES (77, 'Beldandi Rural Municipality', 'Rural Municipality');
