-- Nepal local levels
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (1, 'Bhojpur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (1, 'Shadanand', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (1, 'Hatuwagadhi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (1, 'Ramprasad Rai', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (1, 'Aamchok', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (1, 'Tyamkemaiyunm', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (1, 'Arun', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (1, 'Pauwadungma', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (1, 'Salpasilichho', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (2, 'Dhankuta', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (2, 'Pakhribas', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (2, 'Mahalaxmi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (2, 'Sangurigadhi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (2, 'Sahidbhumi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (2, 'Chhathar Jorpati', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (2, 'Chaubise', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (3, 'Ilam', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (3, 'Deumai', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (3, 'Mai', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (3, 'Suryodaya', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (3, 'Phakphokthum', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (3, 'Chulachuli', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (3, 'Maiwakhola', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (3, 'Mangsebung', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (3, 'Rong', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (3, 'Sandakpur', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (4, 'Bhadrapur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (4, 'Damak', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (4, 'Birtamod', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (4, 'Mechinagar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (4, 'Arjundhara', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (4, 'Kankai', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (4, 'Shivasatakshi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (4, 'Gauradaha', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (4, 'Kamal', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (4, 'Jhapa', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (4, 'Buddhashanti', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (4, 'Haldibari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (4, 'Kachankawal', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (4, 'Barhadashi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (4, 'Gauriganj', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (5, 'Diktel Rupakot Majhuwagadhi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (5, 'Halesi Tuwachung', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (5, 'Khotehang', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (5, 'Diprung Chuichumma', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (5, 'Aiselukharka', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (5, 'Jantedhunga', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (5, 'Kepilasgadhi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (5, 'Barahapokhari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (5, 'Rawabesi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (5, 'Sakela', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (6, 'Biratnagar', '', 'Metropolitan', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (6, 'Sundarharaicha', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (6, 'Belbari', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (6, 'Pathari Sanischare', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (6, 'Ratuwamai', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (6, 'Urlabari', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (6, 'Rangeli', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (6, 'Sunbarshi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (6, 'Letang', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (6, 'Budhiganga', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (6, 'Jahada', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (6, 'Kanepokhari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (6, 'Katahari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (6, 'Dhanpalthan', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (6, 'Gramthan', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (6, 'Kerabari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (6, 'Miklajung', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (7, 'Siddhicharan', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (7, 'Khijidemba', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (7, 'Champadevi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (7, 'Chisankhugadhi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (7, 'Manebhanjyang', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (7, 'Molung', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (7, 'Likhu', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (7, 'Sunkoshi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (8, 'Phidim', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (8, 'Phalelung', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (8, 'Phalgunanda', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (8, 'Hilihang', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (8, 'Kummayak', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (8, 'Miklajung', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (8, 'Tumbeba', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (8, 'Yangwarak', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (9, 'Khandbari', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (9, 'Chainpur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (9, 'Dharmadevi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (9, 'Madi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (9, 'Panchkhapan', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (9, 'Bhotkhola', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (9, 'Chichila', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (9, 'Makalu', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (9, 'Sabapokhari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (9, 'Silichong', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (10, 'Solududhkunda', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (10, 'Khumbu Pasanglhamu', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (10, 'Dudhakaushika', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (10, 'Nechasalyan', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (10, 'Mahakulung', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (10, 'Likhu Pike', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (10, 'Sotang', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (10, 'Thulung Dudhkoshi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (11, 'Dharan', '', 'Sub-Metropolitan', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (11, 'Itahari', '', 'Sub-Metropolitan', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (11, 'Inaruwa', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (11, 'Duhabi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (11, 'Ramdhuni', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (11, 'Barahachhetra', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (11, 'Dewanganj', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (11, 'Koshi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (11, 'Gadhi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (11, 'Barju', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (11, 'Bhokraha Narsing', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (11, 'Harinagar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (12, 'Phungling', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (12, 'Aathrai Tribeni', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (12, 'Sidingba', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (12, 'Phaktanglung', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (12, 'Mikwakhola', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (12, 'Meringden', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (12, 'Maiwakhola', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (12, 'Pathibhara Yangwarak', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (12, 'Sirijangha', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (13, 'Myanglung', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (13, 'Laligurans', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (13, 'Aathrai', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (13, 'Chhathar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (13, 'Phedap', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (13, 'Menchayayem', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (14, 'Triyuga', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (14, 'Katari', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (14, 'Chaudandigadhi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (14, 'Belaka', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (14, 'Udayapurgadhi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (14, 'Tapli', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (14, 'Rautamai', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (14, 'Limchungbung', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (15, 'Rajbiraj', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (15, 'Kanchanrup', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (15, 'Dakneshwori', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (15, 'Bodebarsain', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (15, 'Khadak', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (15, 'Shambhunath', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (15, 'Surunga', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (15, 'Hanumannagar Kankalini', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (15, 'Saptakoshi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (15, 'Agnisair Krishna Savaran', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (15, 'Chhinnamasta', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (15, 'Mahadeva', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (15, 'Tirhut', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (15, 'Tilathi Koiladi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (15, 'Rupani', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (15, 'Balan-Bihul', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (15, 'Bishnupur', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (15, 'Rajgadh', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (16, 'Lahan', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (16, 'Siraha', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (16, 'Golbazar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (16, 'Mirchaiya', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (16, 'Kalyanpur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (16, 'Dhangadhimai', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (16, 'Sukhipur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (16, 'Karjanha', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (16, 'Aurahi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (16, 'Bariyarpatti', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (16, 'Lakshmipur Patari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (16, 'Naraha', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (16, 'Sakhuwanankarkatti', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (16, 'Arnama', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (16, 'Bhagawanpur', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (16, 'Navarajpur', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (16, 'Bishnupur', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (17, 'Janakpurdham', '', 'Sub-Metropolitan', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (17, 'Chhireshwarnath', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (17, 'Ganeshman Charnath', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (17, 'Dhanushadham', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (17, 'Nagarain', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (17, 'Bideha', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (17, 'Mithila', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (17, 'Shahidnagar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (17, 'Sabaila', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (17, 'Kamala', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (17, 'Mithila Bihari', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (17, 'Hansapur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (17, 'Janaknandani', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (17, 'Bateshwar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (17, 'Mukhiyapatti Musharniya', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (17, 'Lakshminiya', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (17, 'Aurahi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (17, 'Dhanauji', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (18, 'Jaleshwar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (18, 'Bardibas', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (18, 'Gaushala', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (18, 'Loharpatti', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (18, 'Ramgopalpur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (18, 'Manara Shiswa', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (18, 'Matihani', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (18, 'Bhangaha', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (18, 'Balwa', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (18, 'Aurahi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (18, 'Ekdara', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (18, 'Sonama', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (18, 'Samsi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (18, 'Mahottari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (18, 'Pipra', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Malangwa', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Hariwan', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Ishwarpur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Lalbandi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Godaita', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Barahathwa', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Haripur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Haripurwa', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Balara', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Kabilasi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Bagmati', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Chakraghatta', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Chandranagar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Dhankaul', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Brahmapuri', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Ramnagar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Basbariya', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Bishnu', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Kaudena', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (19, 'Parsa', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (20, 'Gaur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (20, 'Chandrapur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (20, 'Garuda', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (20, 'Gujara', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (20, 'Gadhimai', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (20, 'Brindaban', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (20, 'Devahi Gonahi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (20, 'Madhav Narayan', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (20, 'Maulapur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (20, 'Katahariya', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (20, 'Paroha', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (20, 'Ishnath', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (20, 'Phatuwa Bijayapur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (20, 'Baudhimai', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (20, 'Rajpur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (20, 'Rajdevi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (20, 'Durga Bhagawati', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (20, 'Yamunamai', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (21, 'Kalaiya', '', 'Sub-Metropolitan', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (21, 'Jitpursimara', '', 'Sub-Metropolitan', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (21, 'Kolhabi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (21, 'Nijgadh', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (21, 'Mahagadhimai', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (21, 'Simroungadh', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (21, 'Pacharauta', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (21, 'Adarsh Kotwal', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (21, 'Karaiyamai', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (21, 'Devtal', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (21, 'Parwanipur', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (21, 'Prasauni', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (21, 'Pheta', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (21, 'Baragadhi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (21, 'Suwarna', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (21, 'Bishrampur', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (22, 'Birgunj', '', 'Metropolitan', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (22, 'Pokhariya', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (22, 'Bahudaramai', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (22, 'Parsagadhi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (22, 'Thori', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (22, 'Jagarnathpur', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (22, 'Dhobini', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (22, 'Chhipaharmai', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (22, 'Pakahamainpur', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (22, 'Bindabasini', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (22, 'Sakhuwa Prasauni', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (22, 'Paterwasugauli', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (22, 'Kalikamai', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (22, 'Jirabhawani', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (27, 'Kathmandu', '', 'Metropolitan', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (27, 'Tokha', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (27, 'Budhanilkantha', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (27, 'Tarakeshwar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (27, 'Gokarneshwar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (27, 'Nagarjun', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (27, 'Chandragiri', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (27, 'Kirtipur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (27, 'Kageshwari Manohara', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (27, 'Shankharapur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (27, 'Dakshinkali', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (29, 'Lalitpur', '', 'Metropolitan', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (29, 'Mahalaxmi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (29, 'Godawari', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (29, 'Konjyosom', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (29, 'Bagmati', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (29, 'Mahankal', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (23, 'Bhaktapur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (23, 'Madhyapur Thimi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (23, 'Suryabinayak', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (23, 'Changunarayan', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (24, 'Bharatpur', '', 'Metropolitan', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (24, 'Ratnanagar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (24, 'Khairahani', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (24, 'Rapti', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (24, 'Kalika', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (24, 'Madi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (24, 'Ichhyakamana', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (30, 'Hetauda', '', 'Sub-Metropolitan', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (30, 'Thaha', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (30, 'Bhimphedi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (30, 'Makawanpurgadhi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (30, 'Manahari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (30, 'Raksirang', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (30, 'Bakaiya', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (30, 'Bagmati', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (30, 'Kailash', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (30, 'Indrasarowar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (28, 'Dhulikhel', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (28, 'Banepa', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (28, 'Panauti', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (28, 'Panchkhal', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (28, 'Namobuddha', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (28, 'Mandandeupur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (28, 'Khani Khola', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (28, 'Chauri Deurali', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (28, 'Temal', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (28, 'Bethanchowk', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (28, 'Bhumlu', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (28, 'Mahabharat', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (28, 'Roshi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (26, 'Chautara Sangachokgadhi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (26, 'Bahrabise', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (26, 'Melamchi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (26, 'Indrawati', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (26, 'Jugal', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (26, 'Panchpokhari Thangpal', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (26, 'Balefi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (26, 'Bhotekoshi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (26, 'Lisankhu Pakhar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (26, 'Sunkoshi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (26, 'Helambu', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (26, 'Tripurasundari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (25, 'Bhimeshwar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (25, 'Jiri', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (25, 'Kalinchok', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (25, 'Gaurishankar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (25, 'Tamakoshi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (25, 'Melung', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (25, 'Bigu', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (25, 'Baiteshwar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (25, 'Sailung', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (24, 'Manthali', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (24, 'Ramechhap', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (24, 'Umakunda', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (24, 'Khandadevi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (24, 'Gokulganga', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (24, 'Doramba Sailung', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (24, 'Likhu Tamakoshi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (24, 'Sunapati', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (23, 'Kamalamai', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (23, 'Dudhauli', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (23, 'Golanjor', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (23, 'Ghyanglekh', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (23, 'Tinpatan', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (23, 'Phikkal', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (23, 'Marin', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (23, 'Sunkoshi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (23, 'Hariharpurgadhi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (31, 'Bidur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (31, 'Belkotgadhi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (31, 'Kakani', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (31, 'Kispang', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (31, 'Tadi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (31, 'Tarakeshwor', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (31, 'Dupcheshwar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (31, 'Panchakanya', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (31, 'Myagang', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (31, 'Shivapuri', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (31, 'Suryagadhi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (31, 'Likhu', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (33, 'Nilakantha', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (33, 'Dhunibeshi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (33, 'Khaniyabas', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (33, 'Gajuri', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (33, 'Galchhi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (33, 'Gangajamuna', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (33, 'Jwalamukhi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (33, 'Thakre', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (33, 'Netrawati Dabjong', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (33, 'Benighat Rorang', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (33, 'Ruby Valley', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (33, 'Siddhalek', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (33, 'Tripurasundari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (32, 'Uttargaya', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (32, 'Kalika', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (32, 'Gosaikunda', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (32, 'Naukunda', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (32, 'Aamachhodingmo', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (38, 'Pokhara', '', 'Metropolitan', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (38, 'Annapurna', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (38, 'Machhapuchhre', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (38, 'Madi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (38, 'Rupa', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (36, 'Gorkha', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (36, 'Palungtar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (36, 'Sulikot', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (36, 'Siranchok', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (36, 'Ajirkot', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (36, 'Aarughat', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (36, 'Gandaki', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (36, 'Chum Nubri', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (36, 'Dharche', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (36, 'Bhimsen Thapa', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (36, 'Shahid Lakhan', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (41, 'Besisahar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (41, 'Sundarbazar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (41, 'Rainas', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (41, 'Madhya Nepal', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (41, 'Kwaholasothar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (41, 'Dudhpokhari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (41, 'Dordi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (41, 'Marsyangdi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (42, 'Byas', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (42, 'Shuklagandaki', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (42, 'Bhanu', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (42, 'Bhimad', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (42, 'Anbukhaireni', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (42, 'Rishing', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (42, 'Ghiring', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (42, 'Devghat', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (42, 'Myagde', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (42, 'Bandipur', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (43, 'Kawasoti', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (43, 'Gaindakot', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (43, 'Devachuli', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (43, 'Madhyabindu', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (43, 'Baudikali', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (43, 'Bulingtar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (43, 'Binayi Tribeni', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (43, 'Hupsekot', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (44, 'Putalibazar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (44, 'Waling', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (44, 'Chapakot', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (44, 'Bhimad Galyang', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (44, 'Bhirkot', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (44, 'Arjunchhauk', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (44, 'Aandhikhola', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (44, 'Kaligandaki', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (44, 'Phedikhola', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (44, 'Biruwa', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (44, 'Harinas', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (45, 'Kushma', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (45, 'Phalebas', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (45, 'Jaljala', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (45, 'Paiyun', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (45, 'Mahashila', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (45, 'Modi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (45, 'Bihadi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (46, 'Baglung', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (46, 'Galkot', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (46, 'Jaimini', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (46, 'Dhorpatan', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (46, 'Bareng', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (46, 'Kathekhola', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (46, 'Tamankhola', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (46, 'Tarakhola', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (46, 'Nisikhola', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (46, 'Badigad', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (39, 'Beni', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (39, 'Annapurna', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (39, 'Dhaulagiri', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (39, 'Mangala', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (39, 'Malika', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (39, 'Raghuganga', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (38, 'Gharapjhong', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (38, 'Thasang', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (38, 'Baragung Muktikshetra', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (38, 'Lomanthang', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (38, 'Lo-Ghekar Damodarkunda', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (37, 'Chame', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (37, 'Nason', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (37, 'Narpa Bhumi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (37, 'Manang Ngisyang', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (56, 'Ghorahi', '', 'Sub-Metropolitan', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (56, 'Tulsipur', '', 'Sub-Metropolitan', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (56, 'Lamahi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (56, 'Gadhawa', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (56, 'Rajpur', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (56, 'Shantinagar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (56, 'Rapti', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (56, 'Banglachuli', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (56, 'Dangisharan', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (56, 'Babai', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (57, 'Nepalgunj', '', 'Sub-Metropolitan', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (57, 'Kohalpur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (57, 'Narainapur', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (57, 'Raptisonari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (57, 'Baijanath', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (57, 'Khajura', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (57, 'Duduwa', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (57, 'Janki', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (58, 'Gulariya', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (58, 'Madhuwan', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (58, 'Rajapur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (58, 'Thakurbaba', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (58, 'Bansgadhi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (58, 'Barbardiya', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (58, 'Badhaiyatal', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (58, 'Geruwa', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (54, 'Butwal', '', 'Sub-Metropolitan', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (54, 'Siddharthanagar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (54, 'Tilottama', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (54, 'Sainamaina', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (54, 'Lumbini Sanskritik', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (54, 'Devdaha', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (54, 'Gaidahawa', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (54, 'Kanchan', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (54, 'Kotahimai', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (54, 'Marchawari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (54, 'Mayadevi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (54, 'Omsatiya', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (54, 'Rohini', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (54, 'Sammarimai', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (54, 'Siyari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (54, 'Suddhodhan', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (55, 'Kapilvastu', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (55, 'Banganga', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (55, 'Buddhabhumi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (55, 'Shivaraj', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (55, 'Krishnanagar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (55, 'Maharajgunj', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (55, 'Mayadevi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (55, 'Yashodhara', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (55, 'Suddhodhan', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (55, 'Bijayanagar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (53, 'Ramgram', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (53, 'Sunwal', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (53, 'Bardaghat', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (53, 'Susta', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (53, 'Palhinandan', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (53, 'Pratappur', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (53, 'Sarawal', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (52, 'Tansen', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (52, 'Rampur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (52, 'Nisdi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (52, 'Purbakhola', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (52, 'Rambha', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (52, 'Mathagadhi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (52, 'Tinau', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (52, 'Bagnaskali', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (52, 'Ribdikot', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (52, 'Rainadevi Chhahara', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (51, 'Sandhikharka', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (51, 'Sitganga', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (51, 'Bhumikasthan', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (51, 'Chhatradev', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (51, 'Panini', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (51, 'Malarani', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (50, 'Resunga', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (50, 'Musikot', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (50, 'Isma', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (50, 'Kaligandaki', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (50, 'Gulmi Durbar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (50, 'Satyawati', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (50, 'Chandrakot', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (50, 'Ruru Kshetra', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (50, 'Chhatrakot', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (50, 'Dhurkot', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (50, 'Madane', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (50, 'Malika', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (49, 'Pyuthan', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (49, 'Swargadwari', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (49, 'Gaumukhi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (49, 'Mandavi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (49, 'Sarumarani', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (49, 'Mallarani', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (49, 'Naubahini', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (49, 'Jhimruk', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (49, 'Ayirabati', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (48, 'Rolpa', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (48, 'Tribeni', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (48, 'Duikholi (Paribartan)', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (48, 'Madi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (48, 'Runtigadhi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (48, 'Lungri', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (48, 'Gangadev', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (48, 'Sunchhahari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (48, 'Thabang', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (48, 'Sunilsmriti', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (47, 'Sisne', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (47, 'Bhume', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (47, 'Putha Uttarganga', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (68, 'Birendranagar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (68, 'Bheriganga', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (68, 'Gurbhakot', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (68, 'Panchapuri', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (68, 'Lekbeshi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (68, 'Chaukune', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (68, 'Barahatal', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (68, 'Chingad', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (68, 'Simta', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (64, 'Narayan', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (64, 'Dullu', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (64, 'Chamunda Bindrasaini', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (64, 'Aathbis', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (64, 'Bhagawatimai', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (64, 'Gurans', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (64, 'Dungeshwar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (64, 'Naumule', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (64, 'Mahabu', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (64, 'Bhairabi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (64, 'Thantikandh', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (67, 'Sharada', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (67, 'Bagchaur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (67, 'Bangad Kupinde', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (67, 'Kalimati', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (67, 'Tribeni', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (67, 'Kapurkot', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (67, 'Chhatreshwari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (67, 'Siddha Kumakh', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (67, 'Kumakh', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (67, 'Darma', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (62, 'Bheri', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (62, 'Chhedagad', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (62, 'Nalgad', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (62, 'Barekot', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (62, 'Kushe', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (62, 'Junichande', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (62, 'Shivalaya', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (66, 'Musikot', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (66, 'Chaurjahari', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (66, 'Aathbiskot', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (66, 'Banfikot', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (66, 'Tribeni', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (66, 'Sanibheri', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (63, 'Khandachakra', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (63, 'Raskot', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (63, 'Tilagufa', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (63, 'Pachaljharana', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (63, 'Sanni Tribeni', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (63, 'Naraharinath', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (63, 'Shubha Kalika', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (63, 'Mahawai', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (63, 'Palata', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (63, 'Chandannath', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (63, 'Kankasundari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (63, 'Sinja', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (63, 'Hima', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (63, 'Tila', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (63, 'Guthichaur', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (63, 'Tatopani', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (63, 'Patarasi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (61, 'Simikot', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (61, 'Namkha', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (61, 'Kharpunath', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (61, 'Sarkegad', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (61, 'Chankheli', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (61, 'Adanchuli', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (61, 'Tanjakot', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (60, 'Chhayanath Rara', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (60, 'Mugum Karmarong', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (60, 'Soru', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (60, 'Khatyad', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (59, 'Thuli Bheri', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (59, 'Tripurasundari', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (59, 'Dolpo Buddha', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (59, 'Shey Phoksundo', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (59, 'Jagadulla', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (59, 'Mudkechula', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (59, 'Kaike', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (59, 'Chharka Tangsong', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (76, 'Dhangadhi', '', 'Sub-Metropolitan', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (76, 'Tikapur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (76, 'Ghodaghodi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (76, 'Lamki Chuha', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (76, 'Bhajani', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (76, 'Godawari', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (76, 'Gauriganga', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (76, 'Janaki', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (76, 'Bardagoriya', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (76, 'Mohanyal', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (76, 'Kailari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (76, 'Joshipur', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (76, 'Chure', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (77, 'Bhimdatta', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (77, 'Punarbas', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (77, 'Bedkot', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (77, 'Mahakali (Dodhara Chandani)', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (77, 'Shuklaphanta', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (77, 'Belauri', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (77, 'Krishnapur', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (77, 'Beldandi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (77, 'Laljhadi', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (73, 'Amargadhi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (73, 'Parshuram', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (73, 'Aalital', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (73, 'Bhageshwar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (73, 'Navadurga', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (73, 'Ajayameru', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (73, 'Ganyapdhura', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (72, 'Dipayal Silgadhi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (72, 'Shikhar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (72, 'Purbichauki', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (72, 'Badikedar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (72, 'Jorayal', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (72, 'Sayal', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (72, 'Aadarsha', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (72, 'Dr. K.I. Singh', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (72, 'Bogtan Phudsil', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (71, 'Mangalsen', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (71, 'Kamalbazar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (71, 'Sanfebagar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (71, 'Panchadewal Binayak', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (71, 'Chaurpati', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (71, 'Mellekh', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (71, 'Bannigadhi Jayagadh', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (71, 'Ramaroshan', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (71, 'Dhankari', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (71, 'Turmakhand', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (70, 'Jaya Prithvi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (70, 'Bungal', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (70, 'Talkot', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (70, 'Masta', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (70, 'Khaptadchhanna', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (70, 'Thalara', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (70, 'Bitthadchir', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (70, 'Surma', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (70, 'Chhabispathibhera', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (70, 'Durgathali', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (70, 'Kedarsyu', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (70, 'Saipal', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (69, 'Badimalika', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (69, 'Tribeni', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (69, 'Budhiganga', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (69, 'Budhinanda', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (69, 'Gaumul', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (69, 'Jagannath', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (69, 'Swamikartik Khapar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (69, 'Chhededaha (Khaptad Chhededaha)', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (69, 'Himali', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (74, 'Dasharathchand', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (74, 'Patan', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (74, 'Melauli', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (74, 'Purchaudi', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (74, 'Sunarya', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (74, 'Sigas', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (74, 'Shivnath', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (74, 'Pancheshwar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (74, 'Dogadakedar', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (74, 'Dilasaini', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (75, 'Mahakali', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (75, 'Shailyashikhar', '', 'Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (75, 'Malikarjun', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (75, 'Apihimal', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (75, 'Duhun', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (75, 'Naugad', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (75, 'Marma', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (75, 'Lekam', '', 'Rural Municipality', 9);
INSERT INTO local_levels (district_id, name, name_np, type, wards) VALUES (75, 'Byas', '', 'Rural Municipality', 9);
